### ISSUE TITLE
Error when running script : the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by kvandenbogaerde** [PieterVO/EvohomeTemperature#1]
Hi,

When I run this script underPython34, I get an error on
userinfo = json.loads(response.content) : the JSON object must be str, not 'bytes'.

How can this be solved ?

Best regards,
Kristof

**Comment by ukdilmah** [comment]
Hi there - I am receiving the same error.  Any help much appreciated.  Thanks

**Comment by ukdilmah** [comment]
I have fixed this - you need to add ".decode('utf-8')" in lines 46 and 78:

 fullData = json.loads(response.content.decode('utf-8'))[0]

**Comment by PieterVO** [comment]
Sorry for the late reaction. I fixed the issue, thank you @ukdilmah!
