### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by scheung38** [PieterVO/EvohomeTemperature#2]
Hi Pieter

I am trying to use plotly to plot OpenWeatherMap with this

```
import pandas as pd
json_str = 'http://api.openweathermap.org/data/2.5/history/city?q=Paris,FR&type=hour&start=1437264000&end=1439942400'
paris = pd.read_json(json_str, typ='series')
```

Any idea how to extract and use plotly to plot it?

Seb

**Comment by PieterVO** [comment]
Sorry for the late answer. Do you also want a stream plot on plotly?

**Comment by scheung38** [comment]
Yes and also something different... A real time interests calculator, say someone owes you money and you want daily calculator
