### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by mnbf9rca** [PieterVO/EvohomeTemperature#3]
I get the following when i run it on ubuntu 14.04:

Traceback (most recent call last):
  File "./EvohomeTemperature.py", line 39, in <module>
    userid = userinfo['userInfo']['userID']
TypeError: list indices must be integers, not str

**Comment by mnbf9rca** [comment]
actualyl forget that - i had my username and password wrong!

**Comment by PieterVO** [comment]
I also have a project where you can monitor the Evohome Temperatures without use of Plotly, but running your own web server. Are you familiar with SQL and Apache? Then I upload all the needed documents and you just need to fill in the database credentials and such.

**Comment by mnbf9rca** [comment]
yes, i am. that would be really helpful, thanks.

r.

**Comment by PieterVO** [comment]
I just uploaded it, if you follow my instructions it should work, let me know
https://github.com/PieterVO/EvohomeTemperatureSite

**Comment by mnbf9rca** [comment]
I decided to try and port this to an Azure Logic App which works really well. I've published my code here: https://github.com/mnbf9rca/AzureEvoHome

**Comment by hnobre** [comment]
Hi Pieter, not sure whether or not you can help me. I just followed your instructions on how to use plotly to monitor and display evohome temperatures but for some reason I'm not getting data in graphs. Looks like the py file is running ok, it opens Plotly (2 graphs actually, one for each of the sensors I have), but no data is loaded. Could you please provide some support? Thanks in advance!
