### ISSUE TITLE
No data loaded

### ISSUE THREAD

**Issue by hnobre** [PieterVO/EvohomeTemperature#4]
Hi Pieter, not sure whether or not you can help me. I just followed your instructions on how to use plotly to monitor and display evohome temperatures but for some reason I'm not getting data in graphs. Looks like the py file is running ok, it opens Plotly (2 graphs actually, one for each of the sensors I have), but no data is loaded. Could you please provide some support? Thanks in advance!

**Comment by PieterVO** [comment]
Hi, it can take some time to appear. Sometimes the data in the graph is only visible with 2 or more data points.

**Comment by hnobre** [comment]
Hi Pieter,
 thanks so much for the prompt response! I'm pretty sure I did something wrong since the script was run this morning and still no data is displayed. Also, it is supposed to retrieve data each 5 mins so there should be something there. I was wondering if apart from plotly user&password and evohome user&password I should include some additional parameter, such as ApplicationID or something like that...
I'm gonna share with you the two plots I got just in case you are able to identify something:
https://plot.ly/~hnobre/6/salon/

Thanks so much once again!

**Comment by PieterVO** [comment]
Are you sure everything is correct? :-)

**Comment by hnobre** [comment]
:-))))
Not sure at all, that's why I'm asking for some help. The current code is able to retrieve something from Evohome since rooms name's are displayed...and also is able to connect to Plotly since something is loaded there (the names of the rooms)... so it is something regarding the data retrieval. Myabe I can send you the code I used so that you can easily check it...?

**Comment by hnobre** [comment]
Hi again Pieter, I have been trying different options since yesterday and no way to get things running. Do you think I could send you the code? I really apologise for the time this is taking to you but it is important to me to get thing working. Thanks in advance

**Comment by PieterVO** [comment]
No problem.
You can send your code to pieter181@gmail.com.

**Comment by hnobre** [comment]
Thanks Pieter! Code sent by mail! :-)

**Comment by PieterVO** [comment]
Hi, seems that there was a lot going wrong.
Normally, everything should be fixed now.
I also made it easier to configure:
- duplicate instructions.ini
- name the duplicate config.ini
- fill in the correct information in the config.ini file
- Done! Run the script :)

Now you can also just pull the updates from github, the config.ini file will be ignored
